---
name: Integrate with Ubuntu machine
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Run your SSH command
        run: |
          ssh -o StrictHostKeyChecking=no eve-ng@34.16.219.156 "ls -l /tmp/"
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          
      - name: Deploy files to server
        run: |
          SERVER_USER="eve-ng"
          SERVER_HOST="34.16.219.156"
          TARGET_DIR=/tmp/git-int

          ssh $SERVER_USER@$SERVER_HOST << 'EOF'
            cd /tmp/git-int
            git pull origin main
            # Restart a service if needed
            sudo systemctl restart myapp-service
          EOF

          echo "Deployment completed successfully!"
