name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  run-linux-commands:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display system information
        run: |
          echo "System Information:"
          uname -a

      - name: Show disk usage
        run: |
          echo "Disk Usage:"
          df -h
